# Konfigurationsdatei für Python Log Checker
# Alle Einstellungen für Cron-Jobs, SMTP und Pfade

# Cron-Job Definitionen
cron_jobs:
  # Erweiterte Backup-Überprüfung (basierend auf checkbackup-Script)
  - name: "advanced_backup_check"
    schedule: "0 6 * * *"  # Täglich um 6:00 Uhr
    script: "advanced_backup_checker.py"
    description: "Erweiterte Backup-Log-Überprüfung mit Datums-Verzeichnissen"
    enabled: true
    
  # Original Backup-Monitor (optional)
  - name: "backup_log_check"
    schedule: "0 7 * * *"  # Täglich um 7:00 Uhr (nach advanced check)
    script: "backup_monitor.py"
    description: "Standard Backup-Log-Überprüfung"
    enabled: false  # Deaktiviert, da advanced_backup_check verwendet wird
    
  - name: "system_log_check"
    schedule: "*/30 * * * *"  # Alle 30 Minuten
    script: "system_monitor.py"
    description: "Überwacht System-Logs"
    enabled: true
    
  - name: "weekly_report"
    schedule: "0 8 * * 1"  # Montags um 8:00 Uhr
    script: "weekly_report.py"
    description: "Erstellt wöchentlichen Bericht"
    enabled: false

# SMTP-Konfiguration für E-Mail-Versand
# WICHTIG: Konfiguration erfolgt jetzt über Umgebungsvariablen (.env Datei)
# Siehe .env.template für alle verfügbaren Variablen
smtp:
  # Diese Werte werden aus Umgebungsvariablen geladen
  # Falls .env nicht vorhanden, werden diese Fallback-Werte verwendet
  server: "smtp.gmail.com"
  port: 587
  use_tls: true
  use_ssl: false
  username: "your-email@gmail.com"
  password: "your-app-password"
  from_email: "your-email@gmail.com"
  from_name: "Log Checker System"
  default_recipients:
    - "admin@example.com"
    - "monitoring@example.com"
  templates:
    error_subject: "[FEHLER] {hostname} - {script_name} - {timestamp}"
    warning_subject: "[WARNUNG] {hostname} - {script_name} - {timestamp}"
    success_subject: "[OK] {hostname} - {script_name} - {timestamp}"

# Pfad-Konfiguration
paths:
  # Externe gemappte Verzeichnisse
  backup_logs: "/app/data/backup"
  system_logs: "/app/data/system"
  
  # Interne Pfade
  scripts_dir: "/app/scripts"
  logs_dir: "/app/logs"
  temp_dir: "/tmp"
  
  # Spezifische Log-Dateien
  log_patterns:
    backup: "backup_*.log"
    system: "syslog*"
    error: "error*.log"

# Logging-Konfiguration
logging:
  # Log-Level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"
  
  # Log-Datei
  file: "/app/logs/log_checker.log"
  
  # Rotation
  max_size_mb: 10
  backup_count: 5
  
  # Format
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"

# Monitoring-Einstellungen
monitoring:
  # Health-Check Intervall (Sekunden)
  health_check_interval: 30
  
  # Timeout für Script-Ausführung (Sekunden)
  script_timeout: 300
  
  # Maximale Anzahl gleichzeitiger Scripts
  max_concurrent_scripts: 3
  
  # Retry-Verhalten
  max_retries: 3
  retry_delay: 60

# Sicherheits-Einstellungen
security:
  # Erlaubte Script-Pfade
  allowed_script_paths:
    - "/app/scripts"
  
  # Maximale Log-Dateigröße (MB)
  max_log_file_size: 100
  
  # Dateierweiterungen für Scripts
  allowed_script_extensions:
    - ".py"

# Erweiterte Backup-Check Konfiguration (basierend auf checkbackup-Script)
advanced_backup_check:
  # Server-Identifikation
  server_name: "Docker-Container"
  
  # Pfade für Log-Überprüfung
  log_directory: "/app/data/logs"  # Basis-Verzeichnis mit Datums-Unterordnern (YYYY-MM-DD)
  output_directory: "/app/logs/logcheck"  # Ausgabe-Verzeichnis für Reports
  
  # Konfigurationsdateien
  logfilelist_path: "/app/config/logfilelist.txt"  # Liste der erforderlichen Log-Dateien
  keywords_path: "/app/config/keywords.txt"        # Schlüsselwörter für Fehlersuche
  
  # Zeitspanne für Überprüfung
  days_to_check: 1      # Anzahl Tage rückwirkend prüfen
  start_day_offset: 0   # Offset für Startdatum (0 = heute)
  
  # E-Mail-Konfiguration
  email_subject_prefix: "Backup-Check"
  
  # Fallback-Konfiguration (falls Dateien nicht gefunden)
  required_log_files:
    - "Administration.log"
    - "Nevaris.log"
    - "Share_MSSQL.log"
  
  error_keywords:
    - "denied"
    - "Denied"
    - "Warn"
    - "warn"
    - "Warning"
    - "fail"
    - "Fail"
    - "error"
    - "Error"
    - "ERROR"
    - "critical"
    - "Critical"
    - "CRITICAL"

# System-Einstellungen
system:
  # Zeitzone
  timezone: "Europe/Berlin"
  
  # Hostname (wird automatisch erkannt, kann überschrieben werden)
  hostname: ""
  
  # Umgebung (development, staging, production)
  environment: "production"